# Generated by Django 2.1.2 on 2019-08-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '化石DB', 'verbose_name_plural': '化石DB'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_10',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_5',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_6',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_7',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_8',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_9',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='item',
            name='i_01_fossil_ID',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_02_category_CD',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='分類CD'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_03_fossil_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_04_nickname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='愛称'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_05_binomen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='学名'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_06_kingdom',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='界'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_07_phylum',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='門'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_08_subphylum',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='亜門'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_09_lass_nm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='綱'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_10_subclass',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='亜綱'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_11_infraclass',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='下綱'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_12_superorder',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='上目'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_13_order',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='目'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_14_suborder',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='亜目'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_15_infraorder',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='下目'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_16_group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='類'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_17_superfamily',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='上科'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_18_family',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='科'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_19_subfamily',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='亜科'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_20_genus',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='属'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_21_subgenus',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='亜属'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_22_part',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='発掘部位'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_23_part_size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='部位サイズ'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_24_estimate_length',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='推定体長'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_25_product_CD',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='産地CD'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_26_zip_CD',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='郵便番号'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_27_prefecture',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='産地(県)'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_28_city',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='産地(市)'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_29_stratum',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='地層'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_30_discovery_date',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='発見年'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_31_discoverer',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='発見者'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_32_discoverer_job',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='発見者職業'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_33_announced_flag',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='発表区分'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_34_announced_date',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='発表年'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_35_reporter',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='報告者'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_36_reporter_job',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='報告者職業'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_37_geologic_CD',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='地質年代CD'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_38_eon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='累代'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_39_era',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='代'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_40_period',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='紀'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_41_epoch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='世'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_42_age',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='期'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_43_year_ago',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='年代'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_44_outline',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='概要'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_45_details',
            field=models.TextField(blank=True, null=True, verbose_name='詳細'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_46_collect_museum',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='所蔵館'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_47_sumple_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='標本番号'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_48_works_cited1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='参考文献1'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_49_works_cited2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='参考文献2'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_50_works_cited3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='参考文献3'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_51_attach1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='添付データ1'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_52_attach1_comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='添付データ1コメント'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_53_attach2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='添付データ2'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_54_attach2_comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='添付データ2コメント'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_55_attach3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='添付データ3'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_56_attach3_comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='添付データ3コメント'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_57_last_update',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='更新日'),
        ),
    ]
