# Generated by Django 2.1.2 on 2019-08-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190818_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='col30_discovery_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='発見年'),
        ),
        migrations.AlterField(
            model_name='item',
            name='col34_announced_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='発表年'),
        ),
    ]
