# Generated by Django 2.1.2 on 2019-08-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190820_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='col57_last_update',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='更新日'),
        ),
    ]
