# Generated by Django 2.1.2 on 2019-08-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190820_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='col32_discoverer_job',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='発見者職業'),
        ),
        migrations.AlterField(
            model_name='item',
            name='col36_reporter_job',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='報告者職業'),
        ),
    ]
