# Generated by Django 2.1.2 on 2019-08-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190820_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='col51_attach1',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='添付データ1'),
        ),
        migrations.AlterField(
            model_name='item',
            name='col53_attach2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='添付データ2'),
        ),
        migrations.AlterField(
            model_name='item',
            name='col55_attach3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='添付データ3'),
        ),
    ]
